import type { Project } from "./types";

export const projects: Project[] = [
  {
    id: "one",
    number: "05",
    title: "Credit Card Onboarding",
    subtitle: "Earning trust in under 5 minutes",
    description: "Designing an onboarding that turns fear of credit into confident activation.",
    category: "UX/UI Design • Product Design",
    period: "2024",
    color: "violet",
    gradient: "from-violet-600 to-purple-500",
    href: "/projects/one",
    stats: [
      { value: "5", label: "Core archetypes" },
      { value: "6", label: "Key steps" },
      { value: "Self-serve", label: "No &ldquo;executive&rdquo;" },
    ],
    featured: true,
    image: "/projects/one.png",
  },
  {
    id: "ruta-sv",
    number: "01",
    title: "Ruta SV",
    subtitle: "El Salvador's first transit app",
    description: "What if a city's entire transit knowledge lived in people's heads?",
    category: "Product Design • Mobile • Offline-first",
    period: "2024",
    color: "blue",
    gradient: "from-neutral-100 to-white",
    href: "/projects/ruta-sv",
    stats: [
      { value: "45K+", label: "Active users" },
      { value: "42", label: "User interviews" },
      { value: "4.6★", label: "App rating" },
    ],
    featured: true,
    image: "/projects/ruta-sv.png",
  },
  {
    id: "dermacare",
    number: "02",
    title: "Dermacare",
    subtitle: "Skincare that starts with understanding",
    description: "A skin specialized pharmacy experience built around personalized assessment and dermatological expertise.",
    category: "Product Design • Mobile • E-commerce",
    period: "2024",
    color: "emerald",
    gradient: "from-emerald-600 to-teal-500",
    href: "/projects/dermacare",
    stats: [
      { value: "87%", label: "Completion" },
      { value: "3.2x", label: "Engagement" },
      { value: " trust", label: "94%" },
    ],
    featured: true,
    image: "/projects/dermacare.png",
  },
  {
    id: "mobile-banking",
    number: "03",
    title: "Mobile Banking Redesign",
    subtitle: "Faster, simpler transactions",
    description: "Reducing friction in everyday banking for 2M+ users.",
    category: "UX Research • Design Systems",
    period: "2023",
    color: "violet",
    gradient: "from-violet-600 to-purple-500",
    href: "/projects/mobile-banking",
    stats: [
      { value: "40%", label: "Faster tasks" },
      { value: "2M+", label: "Users" },
      { value: "45%", label: "More engagement" },
    ],
    featured: false,
    image: "/projects/mobile-banking.png",
  },
  {
    id: "investment-dashboard",
    number: "04",
    title: "Investment Dashboard",
    subtitle: "Complex data, simple decisions",
    description: "Making investment data accessible to everyday users.",
    category: "UI Design • Data Visualization",
    period: "2023",
    color: "amber",
    gradient: "from-amber-500 to-orange-500",
    href: "/projects/investment-dashboard",
    stats: [
      { value: "60%", label: "More investors" },
      { value: "4.8★", label: "User rating" },
      { value: "12", label: "Data widgets" },
    ],
    featured: false,
    image: "/projects/investment-dashboard.png",
  },
];